[jsonupdates]
    task = 'keyedjsonupdate'
    name = 'enrich-event-info'
    poll-time = 20
    log-level = 10
    logger-name = 'jsonupdate-loggger'
    [jsonupdates.json-enrichers.vlan-name]
        name = 'vlan-name'
        dpath-check = 'vlan'
        dpath-upsert =  'vlan-name'
        dpath-extract-key = 'vlan'
        default-value-key = 'UNKNOWN'
        [jsonupdates.json-enrichers.vlan-name.value-dict]
            11  = "Reverse Engineering"
            100 = "LAN"
            102 = "Link_Tin_Bout"
            104 = "AdamOffice"
            111 = "server rack"
            201 = "Cortana actual and management"
            202 = "Master-chief actual and management"
            204 = "Memedawg actual and management"
            220 = "Adams Office 2 Ports"
            221 = "VMs for testing"
            229 = "LAN Services and Third Party"
            303 = "Wireless routers and other systems on home switch"
            305 = "Media Services on Home Switch"
            329 = "LAN Services and Third Party"
            407 = "Cameras and other services - No Access"
            408 = "NFS shared - No Access"
            UNKNOWN = "UNKNOWN"

    [jsonupdates.json-enrichers.vlan-nic]
        name = 'vlan-nic'
        dpath-check = 'vlan'
        dpath-upsert =  'vlan-nic'
        dpath-extract-key = 'vlan'
        default-value-key = 'UNKNOWN'
        [jsonupdates.json-enrichers.vlan-nic.value-dict]
            11 = "vtnet2"
            100 = "vtnet1"
            102 = "vtnet2"
            104 = "vtnet2"
            111 = "vtnet2"
            201 = "vtnet2"
            202 = "vtnet2"
            204 = "vtnet2"
            220 = "vtnet2"
            221 = "vtnet2"
            229 = "vtnet2"
            303 = "vtnet1"
            305 = "vtnet1"
            329 = "vtnet1"
            407 = "vtnet3"
            408 = "vtnet3"
            UNKNOWN = "UNKNOWN"

    [jsonupdates.json-enrichers.router-nic-name]
        name = 'router-nic-name'
        dpath-check = 'vlan'
        dpath-upsert =  'router-nic-name'
        dpath-extract-key = 'vlan'
        default-value-key = 'UNKNOWN'
        [jsonupdates.json-enrichers.router-nic-name.value-dict]
            11 = "opt1"
            100 = "lan"
            102 = "opt1"
            104 = "opt1"
            111 = "opt1"
            201 = "opt1"
            202 = "opt1"
            204 = "opt1"
            220 = "opt1"
            221 = "opt1"
            229 = "opt1"
            303 = "lan"
            305 = "lan"
            329 = "lan"
            407 = "opt11"
            408 = "opt11"
            UNKNOWN = "UNKNOWN"

    [jsonupdates.json-enrichers.router-nic-tap]
        name = 'router-nic-tap'
        dpath-check = 'in_iface'
        dpath-upsert =  'router-nic-tap'
        dpath-extract-key = 'in_iface'
        default-value-key = 'UNKNOWN'
        [jsonupdates.json-enrichers.router-nic-tap.value-dict]
            ens4 = "vtnet1"
            ens10 = "vtnet2"
            ens11 = "vtnet0"
            ens12 = "vtnet3"
            UNKNOWN = "UNKNOWN"
